In [1]:
import numpy as np

In [18]:
d = np.loadtxt('input.txt', dtype=np.int64)

In [19]:
d

array([ 54296, 106942, 137389, 116551, 129293,  60967, 142448, 101720,
        64463, 142264,  68673, 144661, 110426,  59099,  63711, 120365,
       125233, 126793,  61990, 122059,  86768, 134293, 114985,  61280,
        75325, 103102, 116332, 112075, 114895,  98816,  59389, 124402,
        74995, 135512, 115619,  59680,  61421, 141160, 148880,  70010,
       119379,  92155, 126698, 138653, 149004, 142730,  68658,  73811,
        87064,  62684,  93335, 140475, 143377,  98445, 117960,  80237,
       132483, 108319, 104154,  99383, 104685, 114888,  73376,  58590,
       132759, 114399,  77796, 119228, 136282,  84789,  66511,  51939,
       142313, 117305, 139543,  92054,  64606, 139795, 109051,  97040,
        91850, 107391,  60200,  75812,  74898,  64884, 115210,  85055,
        92256,  67470,  90286, 129142, 109235, 117194, 104028, 127482,
        68502,  92440,  50369,  84878])

In [7]:
dt = np.loadtxt('test.txt', dtype=np.int64)

In [8]:
dt

array([    12,     14,   1969, 100756])

In [9]:
dt // 3

array([    4,     4,   656, 33585])

In [11]:
dt / 3 - 2

array([2.00000000e+00, 2.66666667e+00, 6.54333333e+02, 3.35833333e+04])

In [12]:
dt // 3 - 2

array([    2,     2,   654, 33583])

In [15]:
def fcu(data):
    return data // 3 - 2

In [16]:
fcu(dt)

34241

3364035

In [34]:
def fcu2(d, debug=False):
    ft = 0
    f = d // 3 - 2
    if debug: print(f)
    while f > 0:
        ft += f
        f = f // 3 - 2
        if debug: print(f)
    return ft

In [39]:
fcu2(14, debug=True)

2
-2


2

In [38]:
fcu2(1969, debug=True)

654
216
70
21
5
-1


966

In [37]:
fcu2(100756, debug=True)

33583
11192
3728
1240
411
135
43
12
2
-2


50346

In [40]:
vfcu2 = np.vectorize(fcu2)

In [42]:
vfcu2(d).sum()

5043167